---
version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - "gmazoyer"
  labels:
  - "type: housekeeping"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - "gmazoyer"
  labels:
  - "type: housekeeping"
